### PR TITLE
CSSTUDIO-452: color dialog

### PR DESCRIPTION
**Pull request by claudio-rosati**
@kasemir this is a re-implementation of color dialog using the ControlFX PopOver class. I think it works very well, removing the annoying dialog coming over verything else (also another application) every second.

I would like to try it and if you like it, them I'll redesign also the remaining dialogs in the same way.

Just a note: I've implemented the same behaviour (OK, Cancel), but alternatively we can remove alltogether those buttons for an interactive, real-time update of the color property. Let me know what do you think about it.

### CODE REVIEW

**Comment by kasemir** [comment]
Thanks for the suggestion.
Here's the original dialog:

color_dlg

.. and the popup dialog:

color_pop

I like the little details:
 * "Choose  **background** color" instead of generic "Choose color"
 * Spinners for the color values
 * Color indicator for original and currently selected color (doesn't show in screenshot because it's the background color. Needs a line around it)

The "Restore" button is confusing, since it's almost the same as "Cancel". What might be more useful is a "Default" button that resets the property to its default value.

I'm still hesitant to add the dependency, because all those ideas can be added to the dialog as well.

In the phoebus version, I'll update the dialog to have all these ideas, and then compare once more if the popup is adding significant benefit.

**Comment by claudio-rosati** [comment]
- I’ll add the border for the color. 
- The restore is like cancel without closing the popover. It’s also true that it is possible to click on the left circle to restore that color, so I’ll change the button to default. 
- The most important feature is that the popover doesn’t require to be periodically brought to top. This is a really annoying feature of the current dialog implementation and alone is worth the dependency (this is my opinion). But if you extract from library source the code for the popover and made it available as is inside our packages for me is perfectly fine.

**Comment by kasemir** [comment]
Updated the color dialog:

* Use spinner instead of text field
 * Show color name in title
 * Show default color, original color, current color
 * "Default" button to reset to default
 * "Cancel" (= keep original color) on 'Escape' key
 * Locate dialog on top of property, not in center of editor

Note that "Default" resets to the default value of the property. It's not yet another way to "Cancel", for which there is already the cancel button and the Escape key.

The ModalityHack is an SWT/JFX embedding issue, it's no longer necessary for Phoebus (where I just made the ModalityHack a deprecated NOP). With pure JavaFX, the dialog always remains modal and in front.

color

Sorry, I don't see essential added functionality from the ControlFX dependency.

**Comment by claudio-rosati** [comment]
I'm sorry Kay, I don't agree with you.

First because my very problem is the dialog popping up over other application (mostly on Mac where my users develop their OPI). This has to be solved for **Display Builder inside CS-Studio**, until CS-Studio will run on Java 9 and the integration with Display Builder based on  Phoebus is good enough to be used in commissioning and production. These are my orders and I have to follow them, independently if I like them or not.

Moreover the modern UI of the popover is better in letting the users to remember what they are editing, being the popover is arrowed to the edited property. 

This is my last version, without the default button but with the default color close to the current one. I've added the missing border and a pattern background to better understand when the color is not opaque. Original and default colors are clickable to set the current color.

colorpopover

That said, instead of proceed on my own branch (a thing that I don't like because of the possible problems when merging), is it possible to add a mechanism on the WidgetColorPropertyBinding (and then to the other ones for fonts, rules, ...) allowing me to use the popover in my site product and leave your dialog as default implementation?

**Comment by kasemir** [comment]
What is the specific problem with the dialog remaining in the front?
It is a modal dialog. User needs to pick a color, or cancel.
Such a dialog needs to be in the front.

As for details, the UI needs to be obvious.
Buttons like a "Default" button that resets to the default color is fairly obvious.
It is not obvious that a colored circle happens to be clickable.

**Comment by claudio-rosati** [comment]
> What is the specific problem with the dialog remaining in the front?
It is a modal dialog. User needs to pick a color, or cancel.
Such a dialog needs to be in the front.

If you open the dialog the you switch to another application that was in background (e.g. a web browser to read a color value somwhere) then after no more than a second the dialog pops over autonomously, covering what you were looking at before.

> As for details, the UI needs to be obvious.
Buttons like a "Default" button that resets to the default color is fairly obvious.
It is not obvious that a colored circle happens to be clickable.

First the mouse changes when you are over the two external circles and to the captions. Second I can agree on having the buttons, but in this case both Original and Default should be there. I will put them back.

**Comment by kasemir** [comment]
> both Original and Default should be there.

Why would somebody pick "Original"? To abort the change, to not edit the color.
For that, there's already "Cancel".

**Comment by claudio-rosati** [comment]
Here it is:

colorpopover2

Cancel closes the dialog, Original not. So if you are trying to understand which color to use you can revert to original and start over moving the sliders. I think its better to have for symmetry, but I can drop it if you think is confusing.

**Comment by kasemir** [comment]
> .. extract .. code for the popover and made it available as is inside our packages..
I'll look at that, seems better than adding dependency

**Comment by claudio-rosati** [comment]
Good. Tomorrow morning I’ll remove the Original button. A question about the Default button: it should also close the dialog?

**Comment by kasemir** [comment]
I understand your main concern is that the dialog covers other windows.

>  If you open the dialog the you switch to another application that was in background 
> (e.g. a web > browser to read a color value somwhere) ..
> the dialog pops over autonomously, covering what you were looking at before.

I get the same for the ControlsFX PopOver.
See screenshot of editor on Linux. I opened the color PopOver, then a web browser, and the PopOver stays in front of the web browser:

popover

That seems to be the behavior of the underlying JFX PopupControl.

Compared to the dialog, it's even worse:
I can move the dialog to uncover what I need to see on the web page,
but I cannot move the PopOver.

**Comment by claudio-rosati** [comment]
I’ll check on Linux tomorrow. It doesn't happen on Mac where the problem with the dialog occurred. 
The popover can be made movable setting detachable to true, but clearly this is not the point.

**Comment by kasemir** [comment]
I assume you tried Java 8 on Mac. I just tried J9. So we have:
OK: Java 8 and Java 9 on Mac
Not OK: Java 8 on Linux

**Comment by claudio-rosati** [comment]
You'r assuming right, and I can confirm the behaviour you explained.
I think to have found the solution that should please both of us: no dependancies and the usage of my dialog layout in a way that should wark good. I'll try to finish it today (too many meetings this week... I hate not being able to work continuosly for the required time)

**Comment by claudio-rosati** [comment]
@kasemir 
The situation is now the following:

- I was unable to use what I thought be a solution not involving dependencies;
- I've updated the popover in a way that now automatically hides (performing an automatic Cancel action) when clicking outside AND the parent window loose the focus. In this way now the behaviour is identical on Mac and Linux.

If you already included the PopOver class, it should work for you too.

**Comment by kasemir** [comment]
I'm working on a PopOver . Will merge this when I'm done, and then update to use our copy of the PopOver.

**Comment by claudio-rosati** [comment]
OK, good. As soon as it will work I'll take charge to update the other dialogs too.

**Comment by kasemir** [comment]
I'm referring to this:
```
propertyEditor.getScene()
              .getWindow()
              .focusedProperty()
              .addListener(...
```

**Comment by claudio-rosati** [comment]
Ohooops,

Forgot it, sorry. Probably I’ll move it inside the controller where it easy to remove it before hide() is called.

**Comment by kasemir** [comment]
I've added a PopOver class, and replaced the font dialog with a popover.
It's similar to the ControlsFX, but you just pass the content node and call show(owner_node) and hide().
The location, arrow position etc. are handled inside the popover.

Let me know when you're done with the colors so I can merge and update to the bundled popover.

**Comment by claudio-rosati** [comment]
@kasemir I've finished. My implementation uses the `PopOvers` factory class because I cannot (as I've done in my first attempt) put the static `PopOvers.editColor(…)` inside the controller class itself because this class is loaded to create the istance by the `FXMLLoader`, and calling the static method from inside `WidgetColorPropertyBinding` will force OSGi to load the same class by itself, creating a `double loaded class` error when `FXMLLoader` tries to load the `fxml` file and instantiate the controller.
I like to use the `fxml` file approach, that allow a better development of the UI part of the editor. For this reason I thought the `PopOvers` factory class being a good place to put all the editors, becoming the single API access point to them.

**Comment by kasemir** [comment]
One thing I don't like about the FXML approach is that you need to hard-code the OK and Cancel buttons.
Note how the Dialog or also the WidgetFontPopOver use the ButtonBar/ButtonType/ButtonData classes which provide  NLS, 'default' and 'cancel' binding, and assert that the button order follows the OS-specific guidelines.

**Comment by claudio-rosati** [comment]
I understand. Now I'm pressed to finish the DisplayBuilder version of the Thumb Wheel for the Accelerator division. Done that, I'll look at how having the FXML approach together with the ButtonBar/ButtonType/ButtonData, in order to have the best from both of them.

**Comment by kasemir** [comment]
On the focus listener, fundamentally I think it's desired to leave the dialog or popup open:
You edit some display, open the color configuration, then look in a web browser for example colors, using browser and editor side by side. Having the editor or popup close just because the window looses focus is wrong in that case.

Bottom line is that the behavior where the popup remains on top of all windows is a Linux issue beyond our control and hacking around that just makes it worse.

I'll see about the Popups factory class. Should be possible to just have a WidgetColorPopOver just like there's a WidgetFontPopOver.

**Comment by claudio-rosati** [comment]
I've given a quick look and ButtonBar was available from SceneBuilder itself: I was enough ignorant about it to not having already used it. So it should be simbple enough to update the design. I'll do it next week ASAP.

**Comment by kasemir** [comment]
I've merged it, deleted the old color dialog, and updated your code to use the bundled PopOver.
Saw no need for the PopOvers factory, works fine with a WidgetColorPopOver class.

OK on the Button Bar.

**Comment by kasemir** [comment]
For what it's worth, the WidgetColorPopOverController doesn't understand named colors:

 * Create Label. Its foreground color is "Text"
 * Change color to blue. OK
 * Change color to "Text" -> Color is black, not "Text".

The `NamedWidgetColor` is lost, it turns into plain RGBA.

**Comment by claudio-rosati** [comment]
Ok for converting PopOvers into WidgetColorPopOver. I'll do it alltogether next week. I'll also remove (or maybe just comment out) the focus listener.

**Comment by claudio-rosati** [comment]
OK. I'm already doing things now. I've fixed almost everything. I'll look at the named colors too.

**Pull request merged**
