### PR TITLE
CSSTUDIO 161

### PR DESCRIPTION
**Pull request by claudio-rosati**
Location and size displayed inside tracker

### CODE REVIEW

**Comment by claudio-rosati** [comment]
@kasemir, can you check and eventually merge it.
I found the _Location and size displayed inside tracker_ very useful both during development and common usage.

**Comment by kasemir** [comment]
Good idea, I agree that it's useful.

Not sure if that's really a property of the display. Seems to be more like an editor mode. So just like enabling snap-to-grid and/or snap-to-widgets in the toolbar, show-location-and-size could be a toolbar button. Or just enable all the time. Saving that information as a property with individual displays makes less sense to me, but at the same time not important enough for me to do anything about it.

Thanks!

**Comment by claudio-rosati** [comment]
OK, we can decide to move the property on a later time

**Comment by kasemir** [comment]
I just turned it into a toolbar button.
It's really useful, also when using cursor keys to move the tracker pixel by pixel.
I think this eliminates the need for the 'rulers' in BOY, it's actually better since you have the coord right on the widget, no need to glance across the display to the marker on the ruler.

Thanks!

**Pull request merged**
