### PR TITLE
Implemented the search capability.

### PR DESCRIPTION
**Pull request by claudio-rosati**
@kasemir 
Wishing, it is possible add to the left side of the search field a coubple of buttons:

- The first (closest to the search field) is for pinning the search, meaning that when it is selected, each time a new widget is selected the same search is performed (instead of automatically clearing the search). The button is disabled if the search field is empty.
- The second one, when selected force the properties to be alphabetically sorted (inside each category - categories, instead, are not sorted).

What do you think about them?

### CODE REVIEW

**Comment by kasemir** [comment]
I've removed the dependency on org.controlsfx.control.textfield.TextFields since I don't see any benefit from dragging in another library just to create a TextField. Seems to work fine with the plain TextField.

Overall a good idea!

I don't think additional buttons are needed, because just explaining what they'd do takes longer than simply selecting the desired widgets and then performing the property updates once.

**Comment by claudio-rosati** [comment]
TextFields is used to create a clearable text field. As soon as you start typing a clear button appear inside the text field (on the right side). This is not provided  by the standard component.
Moreover, the library comes with the gauges, becaused used in knobs (at least). And it will be used again to substitute the curre colour and fonts (and rules? and actions?) dialogs with the mac-like popup.
I suggest to ripristinate it (for phoebus already exist java 9 version of the library).

**Comment by kasemir** [comment]
I don't consider the 'clearable' feature important enough to add the dependency, will keep the plain text field for now.

Updated once more to preserve the order of fields, so "Widget" properties are still first etc.
(bce6dd0cc0be4bb645b3317cfdc6f84e7bb22935)

**Comment by kasemir** [comment]
Added a ClearingTextField to the phoebus version.

**Comment by claudio-rosati** [comment]
@kasemir 
Yesterday I show to internal ESS user the version with the clearing text field, and the one without it. There was no story, the clearing one was preferred. Moreover I added the Pin Search button and done the same tests with and without it. Users like it mostli in situation where a BOY OPI is imported in Display Builder and has to be reworked.
So for now I'll keep them on my ess-master branch. I think that implementing the new dialogs (colors, fonts...) will require the ControlFX library in any case (the one in gauges) and at that point we can merge again the diverging brances.

**Comment by kasemir** [comment]
Developer of controlsfx has left Oracle & core Java team, so unclear what will become of the library. http://jonathangiles.net/farewell-oracle.

**Comment by kasemir** [comment]
As for "pin", I think that should be the default.
Automatically resetting the search is a bug.
When user enters a search, that should remain active until it's cleared.

**Comment by claudio-rosati** [comment]
> **What about my open source projects / blogs?**
>
>For now I plan to continue blogging here and at FXExperience.com, and to continue the work on my projects like ControlsFX, FXDocs, Scenic View, etc. If or when those plans change, I’ll be sure to make appropriate announcements.

For now I don't think this is a problem. We can always fork the project. One of my tasks is to create an account to Maven Central for ESS libraries (or ESS version of libraries), so this should solve the problem.

**Comment by claudio-rosati** [comment]
I agree on the default for pin. So I'll remove the button and keep only the functionality.
If you agree on having ControlFX included (via org.csstudio.platform.libs.gauges) I'll them do a pull request.

**Comment by kasemir** [comment]
Thanks for the pull request. 'Pin' is now the default, got the updated online help, but implemented all the functionality including 'clear' button without the added dependency.

**Comment by willrogers** [comment]
I agree with avoiding additional dependencies where possible, especially if their future is uncertain.

**Pull request merged**
