### PR TITLE
CSSTUDIO-600: using weak caches for colors and fonts

### PR DESCRIPTION
**Pull request by claudio-rosati**
Tested with the first 10 pages of Display Builder examples:

- Color instances are now 10-20% of the uncached version;
- Fonts instances are now 30-50% of the uncached version;
- Methods where cache is used are at least twice fast then before.

All caches are weak, so when the WidgetColor/WidgetFont keys lose their strong references, the corresponding cached elements could be removed by GC.

### CODE REVIEW

**Comment by kasemir** [comment]
Basically good idea, but
```
   Color c = colorCache.get(color);
    if ( c == null ) {
           synchronized ( colorCache ) {
               // compute color, colorCache.put(..
```
isn't atomic. Two threads can concurrently run into `c == null`, then both add the color, with one being delayed by the sync. section.
Please update to use `ConcurrentHashMap#computeIfAbsent(entry, color -> .. compute the color)` which is non-blocking and atomic.

**Comment by claudio-rosati** [comment]
I'm sorry Kay but I don't agree with you for two reasons.

### Atomicity

Atomicity doesn't mean another thread isn't blocked if the current one is takin' an hour to execute the "atomic" operation. It just means that the client of an atomic operation has not to do explicit synchronisation. Look for the `synchronized` statement inside the `ConcurrentHashMap#computeIfAbsent` code:

```java
public V computeIfAbsent(K key, Function<? super K, ? extends V> mappingFunction) {
        if (key == null || mappingFunction == null)
            throw new NullPointerException();
        int h = spread(key.hashCode());
        V val = null;
        int binCount = 0;
        for (Node<K,V>[] tab = table;;) {
            Node<K,V> f; int n, i, fh;
            if (tab == null || (n = tab.length) == 0)
                tab = initTable();
            else if ((f = tabAt(tab, i = (n - 1) & h)) == null) {
                Node<K,V> r = new ReservationNode<K,V>();
                synchronized (r) {
                    if (casTabAt(tab, i, null, r)) {
                        binCount = 1;
                        Node<K,V> node = null;
                        try {
                            if ((val = mappingFunction.apply(key)) != null)
                                node = new Node<K,V>(h, key, val, null);
                        } finally {
                            setTabAt(tab, i, node);
                        }
                    }
                }
                if (binCount != 0)
                    break;
            }
            else if ((fh = f.hash) == MOVED)
                tab = helpTransfer(tab, f);
            else {
                boolean added = false;
                synchronized (f) {
                    if (tabAt(tab, i) == f) {
                        if (fh >= 0) {
                            binCount = 1;
                            for (Node<K,V> e = f;; ++binCount) {
                                K ek; V ev;
                                if (e.hash == h &&
                                    ((ek = e.key) == key ||
                                     (ek != null && key.equals(ek)))) {
                                    val = e.val;
                                    break;
                                }
                                Node<K,V> pred = e;
                                if ((e = e.next) == null) {
                                    if ((val = mappingFunction.apply(key)) != null) {
                                        added = true;
                                        pred.next = new Node<K,V>(h, key, val, null);
                                    }
                                    break;
                                }
                            }
                        }
                        else if (f instanceof TreeBin) {
                            binCount = 2;
                            TreeBin<K,V> t = (TreeBin<K,V>)f;
                            TreeNode<K,V> r, p;
                            if ((r = t.root) != null &&
                                (p = r.findTreeNode(h, key, null)) != null)
                                val = p.val;
                            else if ((val = mappingFunction.apply(key)) != null) {
                                added = true;
                                t.putTreeVal(h, key, val);
                            }
                        }
                    }
                }
                if (binCount != 0) {
                    if (binCount >= TREEIFY_THRESHOLD)
                        treeifyBin(tab, i);
                    if (!added)
                        return val;
                    break;
                }
            }
        }
        if (val != null)
            addCount(1L, binCount);
        return val;
    }
```

Moreover, if you look carefully at my code, two threads cannot both add the color:

```java
        Color c = colorCache.get(color);
        if ( c == null ) {
            synchronized ( colorCache ) {
                c = colorCache.get(color);
                if ( c == null ) {
                    c = Color.rgb(color.getRed(), color.getGreen(), color.getBlue(), color.getAlpha()/255.0);
                    colorCache.put(color, c);
                }
            }
        }
```

Both threads can pass the first `if` statement, but then only one pass the `synchronized` one. When the second is allowed to, the second `if` will prevent adding the color. This is a common pattern for accessing and updating maps.

### Cache Implementation

The most important argument against `ConcurrentHashMap#computeIfAbsent` (a part the length its implementation) is that the current one uses WeakHashMap, an important feature when you are implementing a cache, because when no strong pointers exist to a key, that key can be claimed by the Garbage Collector, preventing the cache (i.e. the map) to keep indefinitely not used elements.

I don't want to say this is the best cache implementation possible, but a cheaper one, simple enough without requiring importing an external cache library. Given the number of objects to deal with (`main.bob` uses circa 100 colours without the cache, 6 with the cache), I think not exceeding 1000 or so, current implementation seems good enough.

Please let me know what do you think. If you still prefer the `ConcurrentHashMap#computeIfAbsent`, I'll do it.

**Comment by kasemir** [comment]
Google for atomic get-and-set. You check outside the sync section. So two threads can at the same time determine: we need to add the color, it’s not in the hash. Then the first thread adds it, while the second thread blocks. Then the second thread adds it again. You could make the whole method synchronized to get atomic behavior but then you block. ConcurrentHashMap has methods to avoid this, to get atomic add-missing-color-exactly-once without blocking.

**Comment by kasemir** [comment]
Sorry, I'm on vacation w/ spotty internet connection, so slow replies.

>Both threads can pass the first if statement, but then only one pass the synchronized one. 

That's my point: Multiple threads can determine that the entry is missing, and then they all create it, one by one, blocked into sequential order. So N threads can re-create the same entry N times. That could happen in a display that shows 8 motors, all based on the same motor template, so 8 threads loading the same motor file, looking for the same colors in parallel.

Not sure if the weak map makes a big difference. All the displays tend to use the same colors, so caching them once and for all, reducing duplicates, might be the biggest win, as in your example where you reduced the number of copies. Having a few left in the cache even when they're not used right now might not matter. Actually, it might help the next time that forgotten screen is re-opened, where the weak cache would have dropped the entry.

**Comment by claudio-rosati** [comment]
> That's my point: Multiple threads can determine that the entry is missing, and then they all create it, one by one, blocked into sequential order. So N threads can re-create the same entry N times.

Not true. Only the thread that pass both the 2 `if` statements will create the entry. I try to explain better:

- if multiple threads are trying to create the same entry (I mean k.equals(k')), only one will do it, the other will return the uniquely created entry;
- if multiple threads are creating different entries, I agree that some of them can wait.

In any case, profiling the calls to `public static Color convert(final WidgetColor color)` when opening `main.bob` the total time is half the one without cacheing, and the created colours are only 10%.

I will try to follow the code of `ConcurrentHashMap#computeIfAbsent` to see how many `if` and `synchronized` statements will be executed. Moreover with the new refactoring I've done I can easily change the implementation and profiling it. I'm sorry to not have done it before but today I passed the morning at the hospital, and the afternoon in two meetings. I'll do tomorrow morning, and I let you know (I want to create an heavy multi-threading unit test, but I need to expose the cache somehow).

**Comment by kasemir** [comment]
Sorry, I missed the double-check on the phone:
Yes, you check the map once more for the existence of the item inside the sync section, so indeed each entry is only computed and added once.

> I will try to follow the code of ConcurrentHashMap#computeIfAbsent to see how many if
> and synchronized statements will be executed. 
I think the idea is that a synchronized section is very expensive, so the lock-less code in java.util.concurrent tries hard to avoid it. Would be interesting to see how much difference that really makes.

**Comment by kasemir** [comment]
Basic comparison of ConcurrentHashMap and synchronized section to check-then-add-missing:
```
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import javafx.scene.paint.Color;

public class Bench
{
    final static int ENTRIES = 1000000;
    
    final static ConcurrentHashMap<String, Color> cm = new ConcurrentHashMap<>();
    final static Map<String, Color> sm = Collections.synchronizedMap(new HashMap<>());
    
    static void testCM()
    {
        final long start = System.currentTimeMillis();
        for (int i=0; i<ENTRIES; ++i)
            cm.computeIfAbsent("test" + i, nane -> Color.rgb(100, 100, 100));
        final long end = System.currentTimeMillis();
        System.out.println("ConcurrentHashMap: " + (end - start) + "ms");
    }

    static void testSM()
    {
        final long start = System.currentTimeMillis();
        for (int i=0; i<ENTRIES; ++i)
        {
            final String name = "test" + i;
            Color color = sm.get(name);
            if (color == null)
                synchronized (sm)
                {
                    color = sm.get(name);
                    if (color == null)
                    {
                        color = Color.rgb(100, 100, 100);
                        sm.put(name, color);
                    }
                }
        }
        final long end = System.currentTimeMillis();
        System.out.println("synchronized map: " + (end - start) + "ms");
    }

    public static void main(String[] args)
    {
        for (int i=0; i<100; ++i)
        {
            System.out.print("Fill ");
            testCM();
            System.out.print("Hit ");
            testCM();
            cm.clear();
            System.gc();
    
            System.out.print("Fill ");
            testSM();
            System.out.print("Hit ");
            testSM();
            sm.clear();
            System.gc();
        }
    }
}
```

The first few test runs are very different from the following runs. In the end, the ConcurrentHashMap tends to be 25% faster on filling, and 15% slower on getting mapped values. Still, getting values is much faster than filling, and for a cache I figure the ConcurrentHashMap is good: When a value is not in the cache, the  concurrent map doesn't add as much time, and if the value is later on the cache, that's much faster than having no cache. Plus this is for the single-threaded case, where synchronized just adds time. In the multithreaded case, synchronized adds time, plus will block the 'other' thread, reducing the benefits of multithreading.

**Comment by claudio-rosati** [comment]
@kasemir 
I did my tests too (the shown execution time in ms is obtained running the profiler and dividing the profiled Total Tim (CPU) by the Invocations, so it is a mean time between the few write call and the many read ones.

[CacheTests.zip](https://github.com/kasemir/org.csstudio.display.builder/files/1775193/CacheTests.zip)

cache-tests

As you said `ConcurrentHashMap` is the fastest one. The current `WeakHashMap` implementation has the advantage that the GC can claim map elements when the key is no more strongly references (as can be seen in the table above).

So the current status is the following:

- The `WeakHashMap` allows for GC to possibly empty the cache after DB OPIs are closed (most useful in editing).
- The `ConcurrentHashMap` allows for a faster execution, but the cache size can potentially increase indefinitely.

If we want to give more importance to speed, it is be better to switch to `ConcurrentHashMap` as you suggested. If, instead, we want to keep the memory as low as possible, the current implementation is better.

After the refactoring switching to `ConcurrentHashMap` is very easy. Tell me what do you prefer.

**Pull request merged**
