### PR TITLE
Resolves #135

### LINKED ISSUE #135: Drag and Drop needs to be refined.
Once a selected widget is dragged:
- D&D cannot be aborted (undone) via ESC key;
- Editor doesn't scroll as soon as the dragged object is close to editor's borders (I mean outside its scroll pane container);
- D&D should be aborted (undone) if object is released outside the editor's borders (I mean outside its scroll pane container).

Partially related with #132.

### PR DESCRIPTION
**Pull request by claudio-rosati**

### CODE REVIEW

**Comment by kasemir** [comment]
The new AutoScrollHandler uses the  GNU General Public License Version 3. According to https://eclipse.org/legal/eplfaq.php "you may not combine EPL and GPL code..". There are some qualifiers as to how the EPL and GPL code are related, but overall it would be more straight forward to stay with the Eclipse Public License.

**Comment by claudio-rosati** [comment]
Yes, sure.
I'll update my code (and my Eclipse templates), and commit it again.
Thank you

**Comment by kasemir** [comment]
Can you describe how to use the additional D&D support?
From glancing at the code changes, dropping an image should now create a picture widget, but how?
On Linux, when I have an editor open and drag a *.png file from the navigator into the editor, the mouse pointer has the name of the image attached to it, but nothing happens on drop.

**Comment by kasemir** [comment]
When I drag arbitrary text, for example a line highlighted in the Firefox web browser, and drop that in the editor, this will create a label widget, but with empty text.

**Comment by claudio-rosati** [comment]
Hello Kay,

First I've not yet completed this part (file drop is the missing thing that I'll complete tomorrow), and I must improve the "accept-before-drop" part because often Firefox is telling that it is providing something (a string, for example) and then the real string is null.

To try the image (on the stand-alone version), open Safari, search on google for some images and then drag them directly from Safari into the editor.

**Comment by claudio-rosati** [comment]
A last thing, where can I document the D&D support? Is there already a help/html page set I can contribute on?

**Comment by kasemir** [comment]
I've just started to rearrange the online help (online_help branch) to clarify some things.
I'm also merging most of it into one file, similar to the databrowser or scan system, because that has been more practical since it allows printing everything or saving as PDF.
On the downside, it makes it harder to concurrently update different parts of the help, so best prepare your info as plain HTML, but defer adding it to the actual online help for a day until I've merged the ongoing changes.

**Pull request merged**
