### PR TITLE
Thumbwheel updated

### PR DESCRIPTION
**Pull request by claudio-rosati**
- Added example file.
- Contrarily to what said, non spinner-like buttons with +/- icons are used because otherwise navigation with SHIFT+Arrow Keys does not work. I'll address the problem after my Christmas Holidays starting tomorrow with a relocation to a new town.

### CODE REVIEW

**Comment by claudio-rosati** [comment]
Prerequisite: [#63](https://github.com/ControlSystemStudio/cs-studio-thirdparty/pull/63#pullrequestreview-87240525).

@kasemir can you please check now and eventually merge? You should be able to navigate the buttons with SHIFT+arrow keys.

**Comment by kasemir** [comment]
Looks reasonable.

When you add to examples/01_main.bob, please check that the tab order is preserved, 45b8869bfb93643b984dbce9cc7ece147ea1a3e9

In edit mode, it shouldn't update the value. Instead, in edit mode clicking on the widget simply selects it, 13225ebbfc2c40eee6a93febfc2d081fe4b06b96

**Comment by claudio-rosati** [comment]
Edit mode: Ohoops it was on my list and I've just forgot it.
Examples: you're right. I've just added it editing the bob file with a text editor. I'll pay more attention next time. Thank you for telling me.

**Comment by kasemir** [comment]
I used the outline/tree view to move the new button which started out at the end of the list to the suitable location in the tab order.

In general, the display builder's editor and the file format work nicely to minimize file changes. With BOY, what looked like a small change (update label's text, move one widget, add one widget) often ended up creating a very different *.opi file, mostly because the order of properties had changed, then because of the <wuid> or version number updates.
With the display builder, the file changes tend to be limited to just what you would expect.

**Pull request merged**
