### PR TITLE
CSSTUDIO-429 smoothing on rescale

### PR DESCRIPTION
**Pull request by claudio-rosati**
Added explicit smoothing and cacheing set to true for shapes and images.

### CODE REVIEW

**Comment by kasemir** [comment]
Do you have measurements to support this change?
Caching might increase memory usage, and based on the `setCache` javadoc "..on .. GPU accelerated platforms there is little benefit to caching ...".

**Comment by claudio-rosati** [comment]
No. I used in symbols because, after looking at the Medusa code and reading some of the HanSolo blog posts, i thought was fine there being that symbols change in time, and have a good probability to reappear.

Then I've just copied the code on Picture and on the other widgets. I think that memory footprint can be less than a concern due to the very low cost of memory nowadays, but I can remove them if you prefer.

**Comment by claudio-rosati** [comment]
May be we can leave cacheing only when in editor mode (in order to increase speed of pan, zoom, etc.).

**Comment by kasemir** [comment]
Do you have proof from JProfiler, jvisualvm, top, .. that this indeed helps?

Memory _is_ a concern, in fact on SNS beam lines it's the main concern.
Plots and image widgets use a lot of memory, so you can exhaust memory and crash, or incur too many GC runs and slow down, or see UI thread delays in here:
```"JavaFX Application Thread" #1 prio=6 os_prio=0 tid=0x00007f913400a000 nid=0x2883 runnable [0x00007f913bc09000]
css_bl-user_2018-01-29-08-45-53.log-   java.lang.Thread.State: RUNNABLE
css_bl-user_2018-01-29-08-45-53.log-	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
css_bl-user_2018-01-29-08-45-53.log-	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
css_bl-user_2018-01-29-08-45-53.log-	at com.sun.javafx.tk.quantum.QuantumToolkit.createPlatformImage(QuantumToolkit.java:1343)
css_bl-user_2018-01-29-08-45-53.log-	at javafx.scene.image.Image.<init>(Image.java:744)
```

Problem with the JVM is that you can basically only set the max memory.
The JVM then tends to use all that memory as headroom.
So make the max mem too small, and the main operator instance that needs to open several plots simply can't run.
Make the max mem large enough to support the main operator instance, and now _every_ CSS instance on that computer will use the max mem, even the guy who just wants to look at a small screen. So now you've limited the number of CSS instances that can run on the computer.

Run it in the profiler to see where it's using CPU and memory.
To enable caching, you'd likely have to call both `Node.setCache(true)` and `Node.setCacheHint(?which one?)`.
For the RCP version, we have the added complication of hosting JFX inside the SWT FXCanvas.
But even there you can do some testing with the standalone Stage.
Run CSS with `-Dprism.verbose=true -Dprism.showdirty=true` to see which part of the screen it's actually redrawing. Should only be the part that actually changes. Arcs, Polylines, .. are typically static, so they're not redrawn at all. So caching should offer no performance gain at all, yet would use more memory.

Here's the `-Dprism.verbose=true` info I get on my Linux setup:
```
Using java-based Pisces rasterizer
Using dirty region optimizations
Not using texture mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
Prism pipeline name = com.sun.prism.es2.ES2Pipeline
Loading ES2 native library ... prism_es2
	succeeded.
GLFactory using com.sun.prism.es2.X11GLFactory
(X) Got class = class com.sun.prism.es2.ES2Pipeline
Initialized prism pipeline: com.sun.prism.es2.ES2Pipeline
Maximum supported texture size: 16384
Maximum texture size clamped to 4096
Non power of two texture support = true
Maximum number of vertex attributes = 16
Maximum number of uniform vertex components = 16384
Maximum number of uniform fragment components = 16384
Maximum number of varying components = 128
Maximum number of texture units usable in a vertex shader = 32
Maximum number of texture units usable in a fragment shader = 32
Graphics Vendor: Intel Open Source Technology Center
       Renderer: Mesa DRI Intel(R) Haswell Desktop 
        Version: 3.0 Mesa 17.0.1
```

**Comment by claudio-rosati** [comment]
OK, I understand.
After reading a bit more about cache in JavaFX and its usage in animation, I come to the conclusion that is not our case (or possibly it could be just to speedup drawings for zoom with the mouse wheel). So i'll remove it from the pull request.

**Comment by kasemir** [comment]
Does it speed up in the editor for the mouse-wheel zoom?

In that case, it might be useful to enable it for the editor.
Maybe there's a specific container in there that would benefit from caching?
At least on some operating/window systems?
Might also be possible with code like this in the editor that updates all nodes:
```
  for (Node node : model_and_palette.getItems())
  {
      node.setCache(true);
      if (node instanceof Parent)
         //.. recurse into Parent.getChildren()
```

**Comment by claudio-rosati** [comment]
From what I’ve read, pan will benefit a lot because when a complex widget (e.g. Meter) go outside and then inside again only the cached image will be used. Zoom has to be tested. 

One possibility is just set cache on for the display itself when in editor mode and see the performance. Otherwise when widgets are created (possibly in the base class).

**Comment by claudio-rosati** [comment]
Sorry now I’m on my travel back to home and I cannot test it

**Comment by kasemir** [comment]
The scene graph size can be a problem.
That's one reason why the plots are not based on a scene graph, where every tick mark would be a Node, but instead use an image that's updated off the UI thread.
A Meter widget might indeed need caching, in effect becoming similar to the plot. But it would still inflate the scene graph, and perform all drawing on the UI thread. For complex widgets, you're best off drawing an image off the UI thread.

**Comment by kasemir** [comment]
Googling java scene graph performance often points to "use Canvas", but I found that the canvas drawing is still performed on the UI thread. If you think you draw off the UI thread, that just queues the drawing commands for later execution on the UI thread once the canvas is shown.
See org.csstudio.display.builder.representation.javafx.sandbox.Canvas*

**Comment by claudio-rosati** [comment]
So I propose the following:

- merge this PR that is now only focused on smoothing,
- do some tests on setting cache on on all widgets (when the widget is created will be the nice place) only in editor mode and measuring the performances and memory footprint during pan and zoom operations,
- do the same tests, setting cache on only on the most expensive widgets (meters, gauges, knobs, plot, ...),
- evaluate the results and decide it cache is worth or not.

Next week eventually I'll have a fully working linux station (same configuration of the main control room) and I'll be able to install there the development environment end perform tests not only on MacOS X.

**Comment by kasemir** [comment]
> merge this PR that is now only focused on smoothing,

Smoothing is already the default.
See source code of `javafx.scene.shape.Shape`:
```
    private BooleanProperty smooth;

    public final void setSmooth(boolean value) {
        smoothProperty().set(value);
    }

    public final boolean isSmooth() {
        return smooth == null ? true : smooth.get();
    }

    public final BooleanProperty smoothProperty() {
        if (smooth == null) {
            smooth = new StyleableBooleanProperty(true) {

                @Override
                public void invalidated() {
                    impl_markDirty(DirtyBits.NODE_SMOOTH);
                }

                @Override
                public CssMetaData<Shape,Boolean> getCssMetaData() {
                    return StyleableProperties.SMOOTH;
                }

                @Override
                public Object getBean() {
                    return Shape.this;
                }

                @Override
                public String getName() {
                    return "smooth";
                }
            };
        }
        return smooth;
    }
```

So by default, `isSmooth()` will return true.
Calling `setSmooth(true)` uses more memory by allocating a StyleableBooleanProperty, then setting that to true, which is the state that we already had.

**Comment by claudio-rosati** [comment]
That’s funny. Ok, I’ll change to have it only on Picture, where the original problem raised, because the documentation says it’s default is platform dependent, and in our CentOS the default seems to be false (looking very bad when rescaled)

**Comment by claudio-rosati** [comment]
The default I mean is for ImageView. Symbols don’t have the problem because I’ve set to true from the beginning.

**Pull request merged**
