### PR TITLE
First preview of Meters and Guges

### PR DESCRIPTION
**Pull request by claudio-rosati**
The implementation is not yet completed (but I think it is worth a try):
- more properties needs to be added;
- importing BOY equivalents not yet implemented;
- few improvement/fixes to be done.

**NOTE:** [cs-studio-thirdparty#27](https://github.com/ControlSystemStudio/cs-studio-thirdparty/pull/27) and [maven-osgi-bundles#40](https://github.com/ControlSystemStudio/maven-osgi-bundles/pull/40) must be performed first.

### CODE REVIEW

**Comment by claudio-rosati** [comment]
**NOTE:** [cs-studio-thirdparty#27](https://github.com/ControlSystemStudio/cs-studio-thirdparty/pull/27) and [maven-osgi-bundles#40](https://github.com/ControlSystemStudio/maven-osgi-bundles/pull/40) must be performed first.

**Comment by kasemir** [comment]
Don't understand..

I merged it after the preconditions got merged.

The display builder feature.xml should basically have medusa replaced with your libs.gauges reference, but I still see medusa in https://github.com/kasemir/org.csstudio.display.builder/blob/master/org.csstudio.display.builder.feature/feature.xml#L151

**Comment by kasemir** [comment]
Ah, I pushed the 'close' instead of the 'merge' button.
Sorry..

**Comment by claudio-rosati** [comment]
I'll keep the branch until I've finished with it.

**Pull request merged**
