### PR TITLE
Issue 286 rules dialog

### PR DESCRIPTION
**Pull request by claudio-rosati**
Rules dialog workflow redesign completed.

Now is almost possible to setup a rule without using the mouse.

There is a single problem (a bug I've discovered) that I was not able to solve: a NPE occurring when "class" is selected as property to be ruled (I've found where the exception occurs, but just testing the variable for null I think is not correct). Can you Kay give it a look please?

### CODE REVIEW

**Comment by claudio-rosati** [comment]
Kay, walking home I’ve realized I made an error managing focus out of the Expression table. So please wait my next commit (tomorrow morning) before merging. Thank you

**Comment by claudio-rosati** [comment]
@kasemir 
It's ok now to proceed with merge. Thank you.

**Comment by claudio-rosati** [comment]
Technically this will close #286. Anyway, I'll continue to review the remaining dialogs.

**Comment by kasemir** [comment]
I don't understand the PropertyPanelSection changes
```
            field.focusedProperty().addListener(( ob, o, focused ) -> {
                if ( focused ) {
                    combo.requestFocus();
                }
            });
```

When I insert a print, I find that focus listener is never called.
What _would_ make sense: When the macro button is pressed, make the combo editable and then focus on the combo's text editor.

**Comment by claudio-rosati** [comment]
I think you're talking of the EnumWidgetProperty case. In that way when the boolean expression edit is committed, the combo box should have the focus, so a simple SPACE will open the combo popup and one can select with keyboard. I don't think to have tested this particular case (I have to see which widget has an EnumWidgetProperty property).

Without this, nothing is focused, because the "editor" for the following column is a panel (containing the combo and the button).

I agree with you that in the BooleanWidgetProperty case, and i the others where the combo is already editable (because of the macro button being pressed before) being the combo box is already editable, focus request should be followed by a selectAll, in order to have the editable text selected and ready to be changed.

I'll do more tests and eventually add the selection when the combo is editable.

**Comment by kasemir** [comment]
For the EnumWidgetPropertyCase, print when the focus listener is called:
```
field.focusedProperty().addListener((ob, o, focused) ->
{
        System.out.println("Focus: " + focused);
        if (focused)
               combo.requestFocus();
});
```

Then try a Label widget where the Hozizontal Alignment, Vertical Alignment, Rotation are all enum.

--> I haven't seen the printout. The Focus Listener is never called, no matter where I click or how I Tab through the properties.

**Pull request merged**
