### PR TITLE
CSSTUDIO-739: CTRL+click operations problematic on MacOS

### PR DESCRIPTION
**Pull request by claudio-rosati**
Zoom, extending selection with click or rubberbanding, adding points to polyline now working with COMMAND instead of CTRL on MacOS.

### CODE REVIEW

**Comment by kasemir** [comment]
Does it need the check for Mac OS X?
The 'shortcut' handling should automatically select either control or command key depending on the OS, see Javadoc for MouseEvent.isShortcutDown().

**Comment by claudio-rosati** [comment]
Yes you need it, otherwise the CTRL button is selected on the keyboards having both CTRL and CMD. But when you press CTRL you have both your behavior plus the contextual menu.

**Comment by claudio-rosati** [comment]
Sorry for my previous quick answer, I was on the train back home without the possibility to look at javadoc. So, what you suggest is just to remove the platform test... I'll try and test on Mac, linux and Window.

**Comment by claudio-rosati** [comment]
I've successfully tested on MacOS X and Windows. I was unable to test on Linux because after the update, my VM requires being on the ESS network fro the first login, and today I'm at home.

**Comment by kasemir** [comment]
Yes, just replacing `isControlDown` by `isShortcutDown` should do the trick.

**Comment by claudio-rosati** [comment]
Thank you

**Pull request merged**
